### PR TITLE
First Chapter update to branch

### PR DESCRIPTION
**Pull request by james-shively-iii**
Here is my fictional story start.  I will try to merge it and have you guys check it out to see if you like it.  Edit as you see fit.

### CODE REVIEW

**Review by BealBC — CHANGES_REQUESTED** [review]
In line 13, change seen to saw.
In line 13, change open to opened.
In line 14, change the to they.

Once corrected, I will approve and merge the branch. :)

**Comment by daniel-frey** [comment]
One you’re done I’ll add to the story.

**Comment by james-shively-iii** [comment]
I have implemented the edits and I feel its ready to be merged.  Next, Ben will do the next branch for the next chapter, then Dann can do the next.  I hope to have this completed by the end of the day, but I also already submitted this repo link to the assignment since it can constantly change even after being submitted.

**Comment by daniel-frey** [comment]
That seems feasible to me. . . I just have to hunt my way around and figure out how to do it. I’ve used GitHub often, but never for anything like this. .

**Review by daniel-frey — APPROVED** [review]
The changes look good to me! I can't wait for chapter 2 when the world inevitably implodes and then chapter 3 when Tom Cruise and Brad Pitt come save us all from our own destruction.

**Review by BealBC — APPROVED** [review]

**Comment by BealBC** [comment]
Changes approved. James, go ahead and merge it to the master. Ill get to work on Chapter 2 throughout the day.

**Pull request merged**
